packages:
  - apps/*
  - packages/*
  - packages/config/*

catalog:
  "@auth/core": 0.39.0
  "@auth/drizzle-adapter": 1.3.0
  "@babel/core": 7.22.17
  "@babel/preset-env": 7.22.10
  "@babel/preset-react": 7.22.5
  "@babel/preset-typescript": 7.24.1
  "@fortawesome/free-solid-svg-icons": 6.5.2
  "@fortawesome/react-fontawesome": 0.2.0
  "@ianvs/prettier-plugin-sort-imports": 4.1.0
  "@manypkg/cli": 0.21.0
  "@next/bundle-analyzer": 15.3.1
  "@next/eslint-plugin-next": "14.2.3"
  "@playwright/test": 1.52.0
  "@sanity/eslint-config-studio": 5.0.2
  "@sanity/vision": 4.20.3
  "@storybook/addon-essentials": 8.6.12
  "@storybook/addon-interactions": 8.6.12
  "@storybook/addon-links": 8.6.12
  "@storybook/addon-onboarding": 8.6.12
  "@storybook/addon-webpack5-compiler-swc": 3.0.0
  "@storybook/blocks": 8.6.12
  "@storybook/react": 8.6.12
  "@storybook/react-webpack5": 8.6.12
  "@storybook/test": 8.6.12
  "@t3-oss/env-nextjs": 0.6.0
  "@tanstack/react-query": 5.87.1
  "@tanstack/react-query-devtools": 5.87.1
  "@tanstack/react-query-next-experimental": 5.87.1
  "@trpc/client": 11.5.1
  "@trpc/next": 11.5.1
  "@trpc/react-query": 11.5.1
  "@trpc/server": 11.5.1
  "@types/chrome": 0.0.270
  "@types/eslint": "8.56.10"
  "@types/jest": 29.5.14
  "@types/node": 22.15.3
  "@types/react": 19.1.2
  "@types/react-dom": 19.1.3
  "@typescript-eslint/eslint-plugin": "8.48.0"
  "@typescript-eslint/parser": "8.48.0"
  "@xarc/run": 1.1.1
  autoprefixer: 10.4.19
  "babel-jest": 29.7.0
  "class-variance-authority": 0.7.0
  chromatic: 11.5.4
  clsx: 2.1.1
  dotenv: 16.4.4
  "dotenv-cli": 7.4.2
  "drizzle-kit": 0.22.7
  "drizzle-orm": 0.31.2
  eslint: 8.45.0
  "eslint-config-prettier": "9.1.0"
  "eslint-import-resolver-typescript": "3.6.1"
  "eslint-plugin-import": "2.29.1"
  "eslint-plugin-jsx-a11y": "6.9.0"
  "eslint-plugin-no-relative-import-paths": "1.5.5"
  "eslint-plugin-prettier": 5.1.3
  "eslint-plugin-react": "7.34.2"
  "eslint-plugin-react-hooks": "4.6.2"
  "eslint-plugin-react-refresh": "0.4.7"
  "eslint-plugin-sort-keys-fix": "1.1.2"
  "eslint-plugin-storybook": 9.1.5
  "eslint-plugin-typescript-sort-keys": "3.2.0"
  "framer-motion": 11.3.7
  husky: 9.0.11
  "http-server": 14.1.1
  jest: 29.7.0
  "jest-environment-jsdom": 29.7.0
  lerna: 8.1.9
  "lint-staged": 15.2.7
  "lucide-react": 0.378.0
  next: 15.4.8
  "next-auth": 4.24.11
  "next-themes": 0.3.0
  pg: 8.15.6
  postcss: 8.4.38
  postgres: 3.4.4
  prettier: 3.0.0
  "prettier-plugin-packagejson": 2.5.11
  "prettier-plugin-sort-json": 3.0.1
  "prettier-plugin-tailwindcss": 0.6.5
  react: 19.2.1
  "react-dom": 19.2.1
  rimraf: 5.0.7
  sanity: 4.20.3
  storybook: 8.6.12
  "styled-components": 6.1.18
  superjson: 2.2.1
  "tailwind-merge": 1.14.0
  tailwindcss: 3.3.2
  "tailwindcss-animate": 1.0.7
  "ts-node": 10.9.1
  "tsc-alias": 1.8.10
  "tsconfig-paths-webpack-plugin": 4.2.0
  tsdown: 0.15.10
  tsx: 4.16.0
  turbo: 2.0.6
  typescript: 5.9.2
  zod: 3.22.3
