name: Playwright Tests cron
on:
  schedule:
    - cron: "0 * * * *"

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  DATABASE_URL: ${{ secrets.DATABASE_PREVIEW_URL }}
  HOST: https://vubnguyen.com
jobs:
  test-e2e:
    env:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: supersecret
      DISCORD_CLIENT_ID: STUBBED_ID
      DISCORD_CLIENT_SECRET: STUBBED_SECRET
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
